@startuml
'https://plantuml.com/activity-diagram-beta
title Realizar prueba
start
-> Recibir prueba
como parámetro;
repeat :Realizar test;
    : Corregir test;

backward:Siguiente test;
repeat while (¿Hay más tests?) is (Sí) not (No)

:Mostrar resultados;

:Enviar prueba;

stop

@enduml
