@startjson
{
    "_id":{"$oid":"60dc9bd592b241b9bf9aaed6"},
    "info": {
        "trialID": "PRUEBA001",
        "name": "Prueba Ejemplo",
        "description": "Evaluación deterioro cognitivo",
        "userID": "60a44029abf88719b8fb2986",
        "score": 4,
        "maxScore": 7,
        "startTime": {
                            "$numberLong": "1625681526929"
                        }
    },
    "tests": [{
        "isContainsTests": true,
        "maxScore": 4,
        "name": "Visuoespacial/Ejecutiva",
        "parametersNumber": 0,
        "score": 3,
        "startTestTimeOffset": 0,
        "stopTestTimeOffset": 0,
        "testID": "001",
        "testType": 0,
        "tests": [ {
            "expandedScore": [1],
            "h1": "Visuoespacial/Ejecutiva",
            "isContainsTests": false,
            "maxScore": 1,
            "name": "copiarCubo",
            "outputs": ["copiarCubo_60a44029abf88719b8fb2986_1625681526929_draw.jpeg"],
            "outputsNumber": 1,
            "outputsType": ["filename"],
            "parameters": ["cubo.jpg"],
            "parametersNumber": 1,
            "parametersType": ["filename"],
            "score": 1,
            "startTestTimeOffset": 34529,
            "stopTestTimeOffset": 50483,
            "testID": "102",
            "testType": 1,
            "title": "Copiar el dibujo del cubo"
        }, {
            "comment": "Dibuja números incorrectos",
            "expandedScore": [1, 0, 1],
            "h1": "Visuoespacial/Ejecutiva",
            "h2": "Debe marcar las 11 y 10",
            "isContainsTests": false,
            "maxScore": 3,
            "name": "dibujarReloj",
            "outputs": ["dibujarReloj_60a44029abf88719b8fb2986_1625681526929_draw.jpeg"],
            "outputsNumber": 1,
            "outputsType": ["filename"],
            "parameters": ["blank.jpg"],
            "parametersNumber": 1,
            "parametersType": ["filename"],
            "score": 2,
            "scoreOptions": ["Contorno", "Números", "Agujas"],
            "startTestTimeOffset": 56874,
            "stopTestTimeOffset": 74335,
            "testID": "103",
            "testType": 1,
            "title": "Dibujar un reloj"
        }]
    }, {
        "isContainsTests": true,
        "maxScore": 2,
        "name": "Identifiación",
        "parametersNumber": 0,
        "score": 1,
        "startTestTimeOffset": 0,
        "stopTestTimeOffset": 0,
        "testID": "002",
        "testType": 0,
        "tests": [{
            "expandedScore": [0],
            "h1": "Identifiación",
            "isContainsTests": false,
            "maxScore": 1,
            "name": "fotoLeon",
            "outputs": ["recuerdoDiferido01_60a44029abf88719b8fb2986_1625681526929_audio.3gp"],
            "outputsNumber": 1,
            "outputsType": ["filename"],
            "parameters": ["leon.jpeg"],
            "parametersNumber": 1,
            "parametersType": ["filename"],
            "score": 0,
            "startTestTimeOffset": 81856,
            "stopTestTimeOffset": 90640,
            "testID": "301",
            "testType": 3,
            "title": "Nombrar el animal"
        },{
            "comment": "Confunde con camello",
            "expandedScore": [1],
            "h1": "Identifiación",
            "isContainsTests": false,
            "maxScore": 1,
            "name": "fotoDromedario",
            "outputs": ["recuerdoDiferido01_60a44029abf88719b8fb2986_1625681526929_audio.3gp"],
            "outputsNumber": 1,
            "outputsType": ["filename"],
            "parameters": ["dromedario.jpeg"],
            "parametersNumber": 1,
            "parametersType": ["filename"],
            "score": 1,
            "startTestTimeOffset": 129281,
            "stopTestTimeOffset": 147046,
            "testID": "303",
            "testType": 3,
            "title": "Nombrar el animal"
        }]},{
        "expandedScore": [0],
        "h1": "Abstracción",
        "h2": "p.ej. manzana-naranja=fruta",
        "isContainsTests": false,
        "maxScore": 1,
        "name": "Abstracción",
        "outputs": ["recuerdoDiferido01_60a44029abf88719b8fb2986_1625681526929_audio.3gp"],
        "outputsNumber": 1,
        "outputsType": ["filename"],
        "parameters": ["similarities01.png"],
        "parametersNumber": 1,
        "parametersType": ["filename"],
        "score": 0,
        "startTestTimeOffset": 260645,
        "stopTestTimeOffset": 265866,
        "testID": "311",
        "testType": 3,
        "title": "Nombrar similitud entre..."
    }]
}
@endjson